spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    show-sql: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 604800000 # 1 minute 604800000 60000
      refresh-token:
        expiration: 604800000  # 7 days
server:
  port: 7090

stripe:
  secret:
    key: ${STRIPE_KEY}
