name: CI/CD for Psy Backend App

on:
  push:
    branches: [main]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin


      - name: Build Docker Image
        run: docker compose build

      - name: Push to Docker Hub
        run: docker compose push
  
